sudo: required
language: node_js
node_js:
  - 10
services:
- docker
before_script:
- docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PW
script:
- npm version major --no-git-tag-version
- git add package.json
- git commit -m "auto-update by travis [skip ci]"
- git push https://$GH_TOKEN@github.com/nais/nais-testapp HEAD:master
- npm install --production
- make build push
branches:
  only:
  - master
env:
  global:
    secure: aaBdlK/d4wbUkf3KqFsoJrU7MT7iyFSd5shEE/MiQePmMC927f4CokC3mo8dnmoGdBCd5kJN5LOWI7durCi2QnKMw8Jm45VIpyL+n4KuHbkktVLVdSxofUp4lqy2kVxfdS3eghDiyx6X5XN0o6A9MMcuKborPsg91xQDH9TzkIigkvcW0pmw6YPiyz9ogqy6N2UIaluR8iN4Y1b/QGGEWySquIIQ7DqN4uzsZXM1FR29p+Lkq//Ji4sucVJOyAQ8BkdIt6cggtVnwpX+nx1oVhWdnfgV50PfpEM76c2/iQpiJ3xi4H7FGQnqer0bhd409rqd3U5IFD51NLC0DhwCAbeaMOp7BNM3pkXVe/454zwgtn3K8SCwfeb4AO+3jQD9dLPRUD9uu+b4iH26S6VW7mwdvIIKim87/THuPy7mwrzhu7qCMPnO8vlLh7bhEOK9l3tv7axLDoQKIhHWRR+1VRrYUP1A+sDMajMV1mLrr50ZjcAGhCUORA8i/2jo0P4U7MB7+veg/GR6yvdlWK9QP777k1rXqe0sH9JI4TfahL4IqM29Zn8dBnDYsp9VSVfdAdAQL0sfkSyN8gnutpdEjyfO4ktPC9Fwe/6Z4zkLJzREjUFpDDb+NwwSbE28Q+DL3jFromx7OYfpGtxkM4gFnRVB/+mmwB0LT8MTRMbFBYM=
