sudo: required
language: node_js
services:
- docker
before_script:
- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
script:
- npm install --production
- export VERSION=$(node -pe "require('./package.json').version")
- export IMAGE_REF=$(node -pe "require('./package.json').version")
- docker build -t navikt/nais-testapp:${VERSION} .
- docker push 
branches:
  only:
  - master
env:
  global:
  - secure: tAqa9qeLHZPQkUHVbF3limHxDY2YcnyqMcc+10NmJhytdSwcLK0U2FWJ7B2JBg1G/MjPz5ZzLujyNmAwd5bc6iyk4g1+                                      mxLpTz37Sn5oVRys1R4Jey5xiltuSGjYX8HFX3QlwSYvNAjHbr/                                                                                           U6xYix0xjvDxRh1TA43Oejfuoya8pCaR2AteW96JQ6iipdOBG2R1UqC1tnrkfdYYmN75lT6v8ApZMt6pJ66iuIuT5nclx2DXSkt0tm325OOFI9wU0HFxV5Vs/adKYLGs+             OON7O60IyJmhf4G3NwLsJuRZ1fv02/2pxyzRKToZN7lv/9wHcH4TVpQ4uMCs4GgJKANGfOAaLUbsqMVfKhyFPVFHrPN423XeY6GqshfgJqUTEvlItH3H6omJ8opxe+Jz0Fe72BqXbN+   9BBlgTM4DVoGppA1AmlpI9VeI0fvY1RIUfq2xw8qhhm+0q2ib8AqwtpUDELzCc8d4shZspvXpYpf7x7u1UYdu4+Wa1Mk2LJ0T+9zHWwABwMzt/A2XGqj5v04+                     UkauSV3zzS6H3x5eMLOAgQzQ3IUENv7ChbrsWToSUmEdFjKRfXmLzbaX8pX99mX6j8TnoLLE886XjuadVRJYiv3txRpg0qIzRJUAHbkmfH6sFVKdPSGtI/                        76rGbj44oupw66WuwIDh4Bxaij0DNk+i0=
  - secure: aLP9nF9FUyFs33NJhJMrYAW7U5nLsTklI1iLarh11Wf3O1BjcLWrbvpeoJoikTK9keOmDA5OzScJ3E/                                                   9lBoItfmbCUHd0Zz6EmF0rkTGcAZBpO7SYvsWP2c1AcfT7sW6SKwHLlMFO/llIScH5XrB0dC+eigM+hOmWykAtrpVRcb70L65iyf5AZYoAtEBZ1xjSBOMTzUQU/ePY7m3T/           mRb5Zopr6xQQzYvDocuY0EgSU1n+GQxm4QPilzPlzhDF+ruI3i+Y/qiV+mAPodG/J9r1OcklEgXf+jxPbgY+HsZnRqBxSbSc1VHa8nyRBlKMekahRh5t3e3nPFHtAusJ+             UfpZPx5ihYOBwpB+mIx2XAGniNypokXWcCgdTFXvXzU2Pgu6ozcf8YE030VCKVjlQxShqgUCPdOuET+UsWSdYbIBz+6nvNHztPgzjvVvf8kWwwyndaXfMHi/2CE39SszzuenaLd/      IRbRDOu1vRIHxx/CpZ3ly8/CiLex7yuHTUFvBbXKc9O29wJWoCFFSGJzysCPqiOU6W39W5VrU2gDleVVgLK4XWNUSRkRSSooZ12dsLKbddkmSXqKEn7HfAPyPf/                   jyo7AFZgW7oO5N4E91qTsmb40xsg2bpgSdLRDb2gwvag+358+8TI6V+l4Pi7iQoOyd8cFDX5c+OUebvUZtbvE=
