sudo: required
language: node_js
services:
- docker
before_script:
- docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PW
script:
- npm install --production
- export VERSION=$(node -pe "require('./package.json').version")
- docker build -t navikt/nais-testapp:${VERSION} .
- docker push navikt/nais-testapp:${VERSION}
- npm version major --no-git-tag-version
- git add package.json
- git commit -m "auto-update by travis [skip ci]"
- git push https://$GH_TOKEN@github.com/nais/nais-testapp
branches:
  only:
  - master
env:
  global:
  - secure: eNu6byH87n4/5E63nlBWQVTGDdRJE9sR198Sfu+SiS1Bz2xFVz8IRRuML22I7GAn815SEFdbi8haErLOvl7DojrcDLvQVYjth0thFD3kNpkhr8COBEtsD3SpzFbJjPT+ndt6GMQ2srxdIl8Gsle6751LjboCAiRk2iWBueZGh+wqjOBDuqEiweSvBgkTVz8I/z8Gyab0+/yngiaX403TWUHSkYMrgixVR6ujhsDxxcM1NU3nN/GlXXvjQTlbcc8Y2vJQU2zSSpWXO58NGxFPvf/dZYDNsTIxs3TooeFbVELIxHSdqa9e5H0CBhkGt9nbyoP6/Yef3mKQK3T/B6C3WKE209m46yMuMRG1GBiLLe+VRtEmbl2X93AxIe/Ygr+nWMn7Ig6WKHUZ2AP377iLXJ5rNSpJbB8t9grg+CmJ2mS9CSDSqVZY4Z3Q+rmRwYKj2L/Jx/QpusxzaUg9wizthEb4A9+28GEC8HAdwclMMq+etDvS3zF6O0IYZCqLmEqyuDaCQX37+6TjQi5cIa/nbyGEpZix9nkA814Hykyas7zkOcB9pWHWihbCSwNNeHVWVc/TwBWrLcMe8BTpYhSm2PiP/SsbxeJmYt3uDcJosLj5BizhyRc62nQLRPhlwgPZzUPQMzPZsSwtqbTh+bnhI5ceQ0jIrAeqycKsfTp+DBc=
  - secure: BTFVUJq/SCaPIqFs+1kCe8B9wnYrs0WVGdCYhBl6vzKy/VZHDigjJPGxcuTFfBbMphzSmBz8wxWeQTvtgNPjdB6XKpxrCH9d/FAIM1Sf08Ien3JBbMdefyZSVqEp7hrnOSZZGgCR4ISJawo+M2tHQ3qrGBlZ1uGsKUjjFeMHJAtBH8xNBHaGWjhDPoImAqzNV7pPWzIHIK5IecwGuiUFh0mKCm8sdrQoh6yOaW0oNuH1RVSdJfagt35d6xdes6BEjHpmThBX1z43XN0ys3sFScKFH0MQGHTK2FtpTj18pj0LiwYtU3EZjDeOicDfKiCzAcW7Gni7Vb+b/MwG7Y9Juz/gWq4Rc4dud8UPg/hYr3NVwqPKFgcQF1sQomGSVpjwADOMmZ0Cqrd3SuCc4aMpV3MJh21RM+BFy+DJKKj2rxn74FlyWvbUheId6YrKm9SsX0Xp5twfECzY7pZ6aLYJQJRY2j6TerhH8N3xMtJi+nYZPQrRkBTHycIA74+BfyHLi3Ogfgge6hSNBbwSbrVq1GZAvv7A+yJ98hcRZw7jtaVG20uksLQ0prZlkfjIc1nhXgeF2RHbsQSwBznO4RX4yg7v3Ajv+BZuydzfKWKJSJQ3Z9Y3ut+7Tm3Qhls8Dg8Rdb2crKYSqYHIYW/BtlCUVPJx17L18NG5QguuhqZ8Uo8=
  - secure: Otgc+S7jGlTtvkpQXoYvXlZgQ7VeMYrxjwaD1chCuUxp2y7OGf7MV0GwLlO0LkNK+8GXmOVbMQzFK2iqhqzV5El7yCUE8EJpyrMp1zLHsoYHYd+v24ZvkcYe/qin/Ny2uHK7JA+kkXIoeBl46X7L7ZwtxM20YNHYlZ5SUEQ/X58A0zWpdZIx9rRbaRa8ZLNi4PRj5lyyzWSstmPvN08flVaxCufnPndCZSAHoT7Lq0uOlc/zCQ0KTXuoKDV/1jYT6WPuSKl2vzDnTdOyQmHXWzq3chQShKdCym1RQ25InAvxbCnCMBbzLBf5p4/rflwbEHCR6u329MfyRMP4ljLKRjpR2UtvxHu3RLfESsFTqe0C5RGHnwJpip9k25nfYphtApdb2pTXSuzv+CFdVMisnOEdsnqphviKt4zCE/GLgRFToLJ18Gu2c8Pir6geMzkxse0EqoeWhC+5a/M6tzSDj1QbBOLYD3AOUnucBK0Eay/eUdNagkT5KNh/HESES2puu8nXhmScEjXQcy8tV4B5FL8isIrQK0WTKf+TUc6GJN0ELJ1y3KlLjy20xf8csHeKSgbtABnIlqbNl0ZO+jtEaHdZ/y6neegFRx8WB0Uv0sFOJykp83VADdsBCSBlMRsDU6asI1r7yRyZmhG6LG0KiK/TWTm1AoTRfhpG8c5eP1c=
