sudo: required
services:
- docker
before_script:
- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
script:
- npm install --production
- docker build -t navikt/nais-testapp .
branches:
  only:
  - master
env:
  global:
  - secure: tAqa9qeLHZPQkUHVbF3limHxDY2YcnyqMcc+10NmJhytdSwcLK0U2FWJ7B2JBg1G/MjPz5ZzLujyNmAwd5bc6iyk4g1+mxLpTz37Sn5oVRys1R4Jey5xiltuSGjYX8HFX3QlwSYvNAjHbr/U6xYix0xjvDxRh1TA43Oejfuoya8pCaR2AteW96JQ6iipdOBG2R1UqC1tnrkfdYYmN75lT6v8ApZMt6pJ66iuIuT5nclx2DXSkt0tm325OOFI9wU0HFxV5Vs/adKYLGs+OON7O60IyJmhf4G3NwLsJuRZ1fv02/2pxyzRKToZN7lv/9wHcH4TVpQ4uMCs4GgJKANGfOAaLUbsqMVfKhyFPVFHrPN423XeY6GqshfgJqUTEvlItH3H6omJ8opxe+Jz0Fe72BqXbN+9BBlgTM4DVoGppA1AmlpI9VeI0fvY1RIUfq2xw8qhhm+0q2ib8AqwtpUDELzCc8d4shZspvXpYpf7x7u1UYdu4+Wa1Mk2LJ0T+9zHWwABwMzt/A2XGqj5v04+UkauSV3zzS6H3x5eMLOAgQzQ3IUENv7ChbrsWToSUmEdFjKRfXmLzbaX8pX99mX6j8TnoLLE886XjuadVRJYiv3txRpg0qIzRJUAHbkmfH6sFVKdPSGtI/76rGbj44oupw66WuwIDh4Bxaij0DNk+i0=
